name: Continuous Integration
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: docker.io/library/eclipse-temurin:24-jdk-ubi9-minimal
    steps:
      - name: Install dependencies
        run: microdnf -y install git-core maven rpm-libs
      - name: Checkout sources
        uses: actions/checkout@v5
      - name: Maven build
        run: mvn -V -B -Prelease -Dgpg.skip clean install
